AWSTemplateFormatVersion: '2010-09-09'
Description: 'ETL Infrastructure for Data Analysis'

Parameters:
  ExistingGlueRoleName:
    Type: String
    Default: yuval-amar-home-assignment-glue
    Description: Name of the existing IAM role for Glue
  BucketName:
    Type: String
    Default: yuval-amar-data-engineering-assignment
    Description: Name of the existing S3 bucket to store results

Resources:
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: yuval_amar_db

  GlueDailyAverageReturnTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      DatabaseName: yuval_amar_db
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: daily_average_return
        StorageDescriptor:
          Columns:
            - Name: date
              Type: date
            - Name: average_return
              Type: double
          Location: !Sub 's3://${BucketName}/daily_average_return/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Compressed: false
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          typeOfData: file

  GlueHighestWorthTickerTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      DatabaseName: yuval_amar_db
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: highest_worth_ticker
        StorageDescriptor:
          Columns:
            - Name: ticker
              Type: string
            - Name: value
              Type: string
          Location: !Sub 's3://${BucketName}/highest_worth_ticker/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Compressed: false
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          typeOfData: file

  GlueAnnualizedStdDailyReturnsTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      DatabaseName: yuval_amar_db
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: annualized_std_daily_returns
        StorageDescriptor:
          Columns:
            - Name: ticker
              Type: string
            - Name: standard_deviation
              Type: string
          Location: !Sub 's3://${BucketName}/annualized_std_daily_returns/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Compressed: false
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          typeOfData: file

  GlueTopThree30DayReturnTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      DatabaseName: yuval_amar_db
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: top_three_30_day_return
        StorageDescriptor:
          Columns:
            - Name: ticker
              Type: string
            - Name: date
              Type: string
          Location: !Sub 's3://${BucketName}/top_three_30_day_return/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Compressed: false
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          typeOfData: file

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Sub 's3://${BucketName}/etl_scripts/etl_stock_analysis.py'
      DefaultArguments:
        '--job-language': 'python'
        '--job-bookmark-option': 'job-bookmark-enable'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Name: yuval-amar-home-assignment-glue-etl
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ExistingGlueRoleName}'
      GlueVersion: '3.0'
      NumberOfWorkers: 2
      WorkerType: 'G.1X'
  
  GlueCrawler:
    Type: AWS::Glue::Crawler
    DependsOn:
      - GlueDailyAverageReturnTable
      - GlueHighestWorthTickerTable
      - GlueAnnualizedStdDailyReturnsTable
      - GlueTopThree30DayReturnTable
    Properties:
      DatabaseName: yuval_amar_db
      Name: etl-analysis-crawler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ExistingGlueRoleName}'
      Targets:
        S3Targets:
          - Path: !Sub 's3://${BucketName}/daily_average_return/'
          - Path: !Sub 's3://${BucketName}/highest_worth_ticker/'
          - Path: !Sub 's3://${BucketName}/annualized_std_daily_returns/'
          - Path: !Sub 's3://${BucketName}/top_three_30_day_return/'
      Schedule:
        ScheduleExpression: 'cron(0 */4 * * ? *)'
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}}}'

  GlueJobTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: StartETLJobTrigger
      Type: ON_DEMAND
      Description: Trigger to start the ETL job on demand
      Actions:
        - JobName: !Ref GlueJob

Outputs:
  GlueJobName:
    Description: Glue Job Name
    Value: !Ref GlueJob
  GlueDatabaseName:
    Description: Glue Database Name
    Value: yuval_amar_db
  GlueCrawlerName:
    Description: Glue Crawler Name
    Value: !Ref GlueCrawler
  DailyAverageReturnTableName:
    Description: Daily Average Return Table Name
    Value: daily_average_return
  HighestWorthTickerTableName:
    Description: Highest Worth Ticker Table Name
    Value: highest_worth_ticker
  AnnualizedStdDailyReturnsTableName:
    Description: Annualized Std Daily Returns Table Name
    Value: annualized_std_daily_returns
  TopThree30DayReturnTableName:
    Description: Top Three 30 Day Return Table Name
    Value: top_three_30_day_return
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref BucketName
  GlueJobTriggerName:
    Description: Glue Job Trigger Name
    Value: !Ref GlueJobTrigger